# basic options I can say whatever I want following hashtag in Yaml
title: Zipsa Immunology
author: Zipsa
email: zipsaimmunology@gmail.com
description: 집사의 면역학
twitter_username: null
github_username: zipsa

# Build settings
markdown: kramdown
theme: minima
