# basic options I can say whatever I want following hashtag in Yaml
title: Zipsa Immunology
author: Zipsa
email: https://www.facebook.com/immunology001/
description: 집사의 면역학
twitter_username: null
github_username: zipsa

# Build settings
markdown: kramdown
theme: minima
